<?xml version="1.0" encoding="utf-8"?><Database Name="PM" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.BreachList" Member="BreachLists">
    <Type Name="BreachList">
      <Column Name="BreachId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BreachedPassword" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PasswordHash" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Salt" Type="System.Data.Linq.Binary" DbType="VarBinary(32) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PfpPath" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="User_Vault" Member="Vaults" ThisKey="UserId" OtherKey="UserId" Type="Vault" />
      <Association Name="User_Category" Member="Categories" ThisKey="UserId" OtherKey="UserId" Type="Category" />
    </Type>
  </Table>
  <Table Name="dbo.Vault" Member="Vaults">
    <Type Name="Vault">
      <Column Name="VaultId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordEncrypted" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastRotated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Strength" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="User_Vault" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
      <Association Name="Category_Vault" Member="Category" ThisKey="CategoryId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Vault" Member="Vaults" ThisKey="CategoryId" OtherKey="CategoryId" Type="Vault" />
      <Association Name="User_Category" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>